import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Sparkles,
  Wand2,
  ListChecks,
  KeyRound,
  Download,
  CircleUser,
  Loader2,
  Plus,
} from "lucide-react";
import { Card, Badge, Spinner } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Select, Textarea } from "@/components/ui/Select";
import { AccuracyRing } from "@/components/ui/AccuracyRing";
import { useToast } from "@/components/ui/Toast";
import { aiApi, meetingApi, taskApi } from "@/api";
import { apiErrorMessage } from "@/lib/http";
import type { Summary } from "@/types";

const SAMPLE_TRANSCRIPT =
  "Alright team, let's review the Q3 roadmap. The dashboard redesign is on track for next sprint. " +
  "Sam will finalize the analytics charts by Friday. We agreed to move the client demo to Thursday. " +
  "Priya is going to prepare the onboarding flow and share it with design. " +
  "We still need to resolve the JWT refresh bug before release — Alex will own that. " +
  "Let's sync again next Monday to confirm the launch checklist.";

export default function Intelligence() {
  const qc = useQueryClient();
  const push = useToast((s) => s.push);
  const [params, setParams] = useSearchParams();

  const { data: meetings } = useQuery({ queryKey: ["meetings"], queryFn: meetingApi.list });

  // Selected meeting code is reflected in the URL (?m=MT-xxxx) so AI summaries
  // are linkable from the meetings list / dashboard.
  const selected = params.get("m") ?? "";
  const setSelected = (code: string) => setParams(code ? { m: code } : {}, { replace: true });

  // Default to the first meeting once loaded.
  useEffect(() => {
    if (!selected && meetings && meetings.length) setSelected(meetings[0].code);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [meetings]);

  const [transcript, setTranscript] = useState("");

  // Load any existing summary for the selected meeting.
  const { data: existing, isFetching } = useQuery({
    queryKey: ["summary", selected],
    queryFn: () => aiApi.getSummary(selected),
    enabled: !!selected,
    retry: false, // a 404 just means "not generated yet"
  });

  const [summary, setSummary] = useState<Summary | null>(null);
  useEffect(() => {
    setSummary(existing ?? null);
  }, [existing, selected]);

  const generate = useMutation({
    mutationFn: () => aiApi.generateSummary(selected, transcript || SAMPLE_TRANSCRIPT),
    onSuccess: (s) => {
      setSummary(s);
      void qc.invalidateQueries({ queryKey: ["summary", selected] });
      push("Summary generated", "success");
    },
    onError: (err) => push(apiErrorMessage(err), "error"),
  });

  const toggleItem = useMutation({
    mutationFn: ({ itemId, done }: { itemId: string; done: boolean }) =>
      aiApi.toggleActionItem(summary!.id, itemId, done),
    onSuccess: (s) => setSummary(s),
    onError: (err) => push(apiErrorMessage(err), "error"),
  });

  // F03 -> F06 handoff: turn an AI action item into a board task.
  const toBoard = useMutation({
    mutationFn: (item: { text: string; assignee: string }) =>
      taskApi.create({
        title: item.text,
        assignee: item.assignee,
        status: "todo",
        priority: "medium",
        fromMeeting: selected,
      }),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ["tasks"] });
      push("Added to board", "success");
    },
    onError: (err) => push(apiErrorMessage(err), "error"),
  });

  const doneCount = useMemo(
    () => summary?.actionItems.filter((a) => a.done).length ?? 0,
    [summary]
  );

  const exportSummary = () => {
    if (!summary) return;
    const lines = [
      `IntellMeet — Meeting Summary`,
      `Accuracy: ${summary.accuracy}%   Generated by: ${summary.generatedBy}`,
      ``,
      `SUMMARY`,
      summary.summary,
      ``,
      `KEY POINTS`,
      ...summary.keyPoints.map((k) => `• ${k}`),
      ``,
      `ACTION ITEMS`,
      ...summary.actionItems.map(
        (a) => `[${a.done ? "x" : " "}] ${a.text} — ${a.assignee}`
      ),
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `summary-${selected}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <div className="flex items-center gap-3">
        <div className="grid size-10 place-items-center rounded-xl bg-ai-500/15 text-ai-400">
          <Sparkles className="size-5" />
        </div>
        <div>
          <h1 className="font-display text-2xl font-bold text-text-hi">AI Intelligence</h1>
          <p className="text-sm text-text-mid">
            Turn a transcript into a summary and assigned action items.
          </p>
        </div>
      </div>

      {/* Generator */}
      <Card className="p-6">
        <div className="grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end">
          <div>
            <label className="mb-1.5 block text-sm font-medium text-text-mid">Meeting</label>
            <Select value={selected} onChange={(e) => setSelected(e.target.value)}>
              <option value="" disabled>
                Select a meeting…
              </option>
              {meetings?.map((m) => (
                <option key={m.code} value={m.code}>
                  {m.title} ({m.code})
                </option>
              ))}
            </Select>
          </div>
          <Button
            variant="ai"
            onClick={() => generate.mutate()}
            disabled={!selected || generate.isPending}
          >
            {generate.isPending ? (
              <>
                <Loader2 className="size-4 animate-spin" /> Generating…
              </>
            ) : (
              <>
                <Wand2 className="size-4" /> {summary ? "Regenerate" : "Generate summary"}
              </>
            )}
          </Button>
        </div>

        <div className="mt-4">
          <label className="mb-1.5 block text-sm font-medium text-text-mid">
            Transcript{" "}
            <span className="text-text-lo">
              (paste meeting captions, or leave blank to use a sample)
            </span>
          </label>
          <Textarea
            rows={4}
            placeholder={SAMPLE_TRANSCRIPT}
            value={transcript}
            onChange={(e) => setTranscript(e.target.value)}
          />
        </div>
      </Card>

      {/* Results */}
      {isFetching && !summary ? (
        <div className="grid h-40 place-items-center">
          <Spinner className="size-6 text-ai-400" />
        </div>
      ) : summary ? (
        <div className="grid gap-5 lg:grid-cols-3">
          {/* Summary + key points */}
          <div className="space-y-5 lg:col-span-2">
            <Card className="p-6">
              <div className="flex items-start justify-between gap-4">
                <h2 className="font-display font-semibold text-text-hi">Summary</h2>
                <Button variant="ghost" size="sm" onClick={exportSummary}>
                  <Download className="size-4" /> Export
                </Button>
              </div>
              <p className="mt-3 text-sm leading-relaxed text-text-mid">{summary.summary}</p>
            </Card>

            <Card className="p-6">
              <h2 className="flex items-center gap-2 font-display font-semibold text-text-hi">
                <KeyRound className="size-4 text-signal-400" /> Key points
              </h2>
              <ul className="mt-3 space-y-2">
                {summary.keyPoints.map((k, i) => (
                  <li key={i} className="flex gap-2.5 text-sm text-text-mid">
                    <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-signal-500" />
                    {k}
                  </li>
                ))}
              </ul>
            </Card>
          </div>

          {/* Sidebar: accuracy + action items */}
          <div className="space-y-5">
            <Card className="flex items-center gap-4 p-5">
              <AccuracyRing value={summary.accuracy} />
              <div>
                <div className="text-sm font-medium text-text-hi">Summary accuracy</div>
                <div className="text-xs text-text-lo">
                  {summary.accuracy >= 85 ? "Meets the >85% target" : "Below target"}
                </div>
                <Badge tone={summary.generatedBy === "openai" ? "ai" : "muted"} className="mt-1.5">
                  {summary.generatedBy === "openai" ? "OpenAI" : "Mock AI"}
                </Badge>
              </div>
            </Card>

            <Card className="p-5">
              <div className="flex items-center justify-between">
                <h2 className="flex items-center gap-2 font-display font-semibold text-text-hi">
                  <ListChecks className="size-4 text-ai-400" /> Action items
                </h2>
                <span className="text-xs text-text-lo">
                  {doneCount}/{summary.actionItems.length}
                </span>
              </div>
              <div className="mt-3 space-y-2">
                {summary.actionItems.map((a) => (
                  <label
                    key={a.id}
                    className="flex cursor-pointer items-start gap-3 rounded-lg border border-line bg-ink-850/40 p-3 transition-colors hover:border-ink-600"
                  >
                    <input
                      type="checkbox"
                      checked={a.done}
                      onChange={(e) => toggleItem.mutate({ itemId: a.id, done: e.target.checked })}
                      className="mt-0.5 size-4 shrink-0 accent-signal-500"
                    />
                    <span className="min-w-0 flex-1">
                      <span
                        className={`block text-sm ${
                          a.done ? "text-text-lo line-through" : "text-text-hi"
                        }`}
                      >
                        {a.text}
                      </span>
                      <span className="mt-0.5 inline-flex items-center gap-1 text-xs text-text-lo">
                        <CircleUser className="size-3" /> {a.assignee}
                      </span>
                    </span>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.preventDefault();
                        toBoard.mutate({ text: a.text, assignee: a.assignee });
                      }}
                      className="shrink-0 rounded-md p-1 text-text-lo transition-colors hover:bg-ink-700 hover:text-signal-400"
                      title="Add to project board"
                      aria-label="Add to project board"
                    >
                      <Plus className="size-4" />
                    </button>
                  </label>
                ))}
              </div>
            </Card>
          </div>
        </div>
      ) : (
        <Card className="flex flex-col items-center gap-3 p-12 text-center">
          <div className="grid size-12 place-items-center rounded-xl bg-ink-700 text-text-lo">
            <Sparkles className="size-6" />
          </div>
          <p className="text-text-mid">
            No summary yet for this meeting. Generate one above.
          </p>
        </Card>
      )}
    </div>
  );
}
